// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/profile.get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/profile.patch').default>>>>
    }
    '/api/auth/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/stats.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.17.7_@types+node@20.19.9_@vue+compiler-sfc@3.5.18_eslint@8.57.1_typescript@5.8.3_vite@7.0.6/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}