// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/7/24 16:32:46
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/zhangyanhua/Desktop/AI/inspire-ai-nexus/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyanhua/Desktop/AI/inspire-ai-nexus/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyanhua/Desktop/AI/inspire-ai-nexus/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyanhua/Desktop/AI/inspire-ai-nexus/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyanhua/Desktop/AI/inspire-ai-nexus/plugins/**/*.{js,ts,mjs}","/Users/zhangyanhua/Desktop/AI/inspire-ai-nexus/composables/**/*.{js,ts,mjs}","/Users/zhangyanhua/Desktop/AI/inspire-ai-nexus/utils/**/*.{js,ts,mjs}","/Users/zhangyanhua/Desktop/AI/inspire-ai-nexus/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyanhua/Desktop/AI/inspire-ai-nexus/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyanhua/Desktop/AI/inspire-ai-nexus/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;