// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsrqdvzwaqycpmxvitai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcnFkdnp3YXF5Y3BteHZpdGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjk4ODAsImV4cCI6MjA2ODc0NTg4MH0.4ulPt4pLC5-ShY-j5LTNcSRHXLpGSAAKtEqyoDPGG6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});